### ISSUE TITLE
css布局技巧-学习总结

### ISSUE THREAD

**Issue by lounj** [lounj/blog#8]
##### 1.Flexbox实现水平垂直居中
  1.1.Flex容器和Flex项目上设置对齐方式
```
  <!-- HTML -->
    <div class="flex-container">
      <div class="flex-item"></div>
    </div>
```
```css
  .flex-container {
    display: flex;
    justify-content: center;
    align-items: center;
  }
 ```
  这样可以很好的实现单个内容在容器中水平垂直居中，
  修改
  ```css
    .flex-container {
      display: inline-flex;
      justify-content: center;
      align-items: center;
    }
  ```
  这样可以容易实现多个内容并排一行在容器内水平垂直居中。
  在上述情况下若添加 flex-direction: column,可以实现多行水平垂直居中。

  1.2.Flexbox布局中，另一种方式实现水平垂直居中
  ```
    <!-- HTML -->
      <div class="flex-container">
        <div class="flex-item"></div>
      </div>
  ```
  ```css
    .flex-container {
      display: flex;
      justify-content: center;
    }

    .flex-item {
      align-self: center;
    }
  ```
  除此之外，还可以使用place-content: center让Flex项目实现水平垂直居中：
  ```css
    .flex-container {
      display: flex;
      place-content: center;
    }

    .flex-item {
      align-self: center;
    }
  ```
  或者上面第一种方式可以换成下面这样：
  ```css
    .flex-container {
      display: inline-flex;
      place-content: center;
      place-items: center;
    }
  ```

  解析：place-content和place-items:
  place-content是align-content和justify-content的简写属性；而place-items是align-itemms和justify-items的简写属性。
  即：
  ```
    .flex-container {
      display: flex;
      place-content: center;
      place-items: center;
    }
  ```
  等效于
  ```css
    .flex__container {
      display: flex;
      align-content: center;
      justify-content: center;

      align-items: center;
      justify-items: center;
    }
  ```
  虽然扩展出来有四个属性，单最终等效于：
  ```css
    .flex__container {
      display: flex;
      justify-content: center;
      align-items: center;
    }
  ```
  1.3.在Flex项目上设置margin：auto；
  ```css
    .flex-container {
      display: flex;
    }
    .flex-item {
      margin: auto;
    }
  ```
  同样只设置单个方向的margin可以得到不同的布局：
  这里需要有一个示例  [参考链接](https://codepen.io/airen/embed/gOPoqRq)
 ##### 二.grid中实现水平垂直居中
  和Flexbox类似
